spring.application.name=quote-api
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:PRACTICAL}
spring.datasource.username=${DB_USERNAME:dummy}
spring.datasource.password=${DB_PASSWORD:dummy123}
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true